### ISSUE TITLE
Move Discord Alerts to Slack

### ISSUE THREAD

**Issue by BirgitPohl** [confio/matadores-backlog-collection#1]
Note: Since we are mainly using Slack, our alerting should be there as well. New Confio members also don't have access to Discord but might be dependent on the alerting.

As a contributor, I want alerts to be in Slack so that I can keep being informed without needing Discord.

## Acceptance Criteria
- All alerts regarding Tgrade is moved into Slack channels

**Comment by migmeneses** [comment]
slab documentation:
https://confio.slab.com/posts/alerting-rules-wip-mr8urybz
